# 50 numpy exercises

#### Creation of hint (Do not modify this block!)

In [ ]:
def ktx_to_dict(input_file, keystarter='<'):
    """ parsing keyed text to a python dictionary. """
    answer = dict()

    with open(input_file, 'r+', encoding='utf-8') as f:
        lines = f.readlines()

    k, val = '', ''
    for line in lines:
        if line.startswith(keystarter):
            k = line.replace(keystarter, '').strip()
            val = ''
        else:
            val += line

        if k:
            answer.update({k: val.strip()})

    return answer

QHA = ktx_to_dict('question.ktx')

def hint(n):
    print(QHA[f'h{n}'])

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.version.version)

1.21.5


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
a=np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
print(a.size)

10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
b=np.zeros(10)
b[4]=1

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [18]:
c=np.zeros(40)
for i in range(0, 40):
    c[i]=i+10

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:
d=np.arange(10)[::-1]

[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [21]:
e=np.arange(0, 9)
e.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [23]:
f=[1, 2, 0, 0, 4, 0]
g=np.nonzero(f)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [26]:
h=np.eye(3, dtype=int)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [31]:
i=np.random.rand(3, 3, 3)

[[[0.27182604 0.06466225 0.3821552 ]
  [0.71844269 0.30700645 0.70945268]
  [0.13796763 0.35755682 0.90645962]]

 [[0.5394114  0.00204239 0.22258634]
  [0.44587501 0.09882783 0.21602747]
  [0.35534278 0.99219017 0.74258994]]

 [[0.0361648  0.69260917 0.03871219]
  [0.94094207 0.85491201 0.11270232]
  [0.34949342 0.52875246 0.40572396]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [28]:
j=np.random.random((10, 10))
minimum=np.amin(j)
maximum=np.amax(j)
print("minimum : %.2f, maximum : %.2f" %(minimum, maximum))

minimum : 0.02, maximum : 0.99


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [31]:
k=np.random.random(30)
avg=np.mean(k)

0.5106787462971366


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [39]:
l=np.ones((5,5))
l[1:-1, 1:-1]=0
print(l)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [2]:
m = np.ones((3,3))
n = np.pad(m, pad_width=1, mode='constant', constant_values=0)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [2]:
nan
False
False
nan
True
False

NameError: name 'nan' is not defined

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [6]:
x=np.diag([1, 2, 3, 4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [9]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [12]:
x=np.unravel_index(99, (6, 7, 8))
print(x)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [13]:
x=[0, 1]
y=np.tile(x, (4, 4))
print(y)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [21]:
x=np.random.random((5, 5))
y=(x-np.mean(x))/np.std(x)
print(y)

[[-1.11459475  1.55874288  1.35659385 -1.17563815 -1.23073404]
 [-0.48835319  1.47545365 -0.37021955 -0.17568242  0.49977108]
 [ 0.83783182 -0.71036618 -1.01628661  0.5379152  -1.35730074]
 [-0.40803101 -0.67238809 -1.28123238  0.62239395  1.38149185]
 [ 1.26209125 -0.82731488  0.65661873  1.2988537  -0.65961595]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [26]:
x = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])
print(x)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\Hyejin_Hwang\AppData\Local\Temp\ipykernel_12964\2330365834.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [28]:
x=np.random.random((5, 3))
y=np.random.random((3, 2))
z=np.dot(x, y)
print(z)

[[0.21554068 0.33324165]
 [0.63296648 0.93348511]
 [0.40201653 0.52902601]
 [0.55080687 0.73159121]
 [0.52377561 0.72491897]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [54]:
x=np.arange(11)
x[(3 < x)&(x<= 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
9
10

hint: np.sum


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z=np.arange(10)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

No hints provided...


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [47]:
nan
0
[-2.14748365e+09]

nan
0
[-2.14748365e+09]


C:\Users\Hyejin_Hwang\AppData\Local\Temp\ipykernel_12964\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\Hyejin_Hwang\AppData\Local\Temp\ipykernel_12964\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [49]:
x=np.random.uniform(-10, +10, 10)
y=np.abs(x)
y=np.ceil(y)
x=np.copysign(y, x)
print(y)

[2. 9. 5. 6. 5. 1. 3. 6. 3. 8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [52]:
x=np.random.randint(1,10, 5, dtype=int)
y=np.random.randint(1,10, 5, dtype=int)
print(np.intersect1d(x, y))

[1 2 6]
